// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";
import { MainSuspenseWrapper } from "./components/SuspenseWrapper";
import { UserGuard } from "./app/auth/UserGuard";

const AdminPage = lazy(() => import("./pages/AdminPage"));
const AdminSetupPage = lazy(() => import("./pages/AdminSetupPage"));
const App = lazy(() => import("./pages/App"));
const DealerDetailPage = lazy(() => import("./pages/DealerDetailPage"));
const DealerManagementPage = lazy(() => import("./pages/DealerManagementPage"));
const GamePage = lazy(() => import("./pages/GamePage"));
const AuthPage = lazy(() => import("./pages/AuthPage"));
const Logout = lazy(() => import("./pages/Logout"));
const ProfilePage = lazy(() => import("./pages/ProfilePage"));
const ShopPage = lazy(() => import("./pages/ShopPage"));
const PaymentSuccess = lazy(() => import("./pages/PaymentSuccess"));
const PaymentCancel = lazy(() => import("./pages/PaymentCancel"));

export const userRoutes: RouteObject[] = [
	{ path: "/admin-page", element: <MainSuspenseWrapper><UserGuard><AdminPage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/adminpage", element: <MainSuspenseWrapper><UserGuard><AdminPage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/admin-setup", element: <MainSuspenseWrapper><AdminSetupPage /></MainSuspenseWrapper>},
	{ path: "/", element: <MainSuspenseWrapper><App /></MainSuspenseWrapper>},
	{ path: "/dealer-management", element: <MainSuspenseWrapper><UserGuard><DealerManagementPage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/dealer-detail/:dealerId", element: <MainSuspenseWrapper><UserGuard><DealerDetailPage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/game/:dealerId", element: <MainSuspenseWrapper><UserGuard><GamePage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/game-page", element: <MainSuspenseWrapper><UserGuard><GamePage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/gamepage", element: <MainSuspenseWrapper><UserGuard><GamePage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/login", element: <MainSuspenseWrapper><AuthPage /></MainSuspenseWrapper>},
	{ path: "/logout", element: <MainSuspenseWrapper><Logout /></MainSuspenseWrapper>},
	{ path: "/profile", element: <MainSuspenseWrapper><UserGuard><ProfilePage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/register", element: <MainSuspenseWrapper><AuthPage /></MainSuspenseWrapper>},
	{ path: "/shop", element: <MainSuspenseWrapper><UserGuard><ShopPage /></UserGuard></MainSuspenseWrapper>},
	{ path: "/payment/success", element: <MainSuspenseWrapper><UserGuard><PaymentSuccess /></UserGuard></MainSuspenseWrapper>},
	{ path: "/payment/cancel", element: <MainSuspenseWrapper><UserGuard><PaymentCancel /></UserGuard></MainSuspenseWrapper>},
];
